services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: doable_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: doable_development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "80"]

volumes:
  mysql_data:
  bundle_cache: